name: Linux CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install egl
      run: sudo apt update; sudo apt install libegl1-mesa-dev

    - name: Clone Dotrix repo
      run: git clone https://github.com/lowenware/dotrix ../dotrix

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --workspace --verbose

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
